spring:
  application:
    name: channel-niubiz-demo-v1

application:
  #  ███████╗██╗██╗██╗ █████╗  ██████╗  ██████╗ ███████╗██████╗
  #  ██╔════╝██║██║██║██╔══██╗██╔════╝ ██╔════╝ ██╔════╝██╔══██╗
  #  ███████╗██║██║██║███████║██║  ███╗██║  ███╗█████╗  ██████╔╝
  #  ╚════██║██║██║██║██╔══██║██║   ██║██║   ██║██╔══╝  ██╔══██╗
  #  ███████║╚██████╔╝██║  ██║╚██████╔╝╚██████╔╝███████╗██║  ██║
  #  ╚══════╝ ╚═════╝ ╚═╝  ╚═╝ ╚═════╝  ╚═════╝ ╚══════╝╚═╝  ╚═╝
  swagger:
    title: API Channel Niubiz Demo V1
    description: API Channel Niubiz Demo V1 project.
    version: 1.0.0
